DEL Crow.Library\bin\*.* /S /q
DEL Crow.Library\obj\*.* /S /q
DEL Crow.Library.Foundation\bin\*.* /S /q
DEL Crow.Library.Foundation\obj\*.* /S /q
DEL CrowSample\bin\*.* /S /q
DEL CrowSample\obj\*.* /S /q
DEL packages\*.* /S /q
DEL Binaries\*.* /S /q
rd Binaries /S /q
rd packages /S /q